apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: healthcheckservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: healthcheckservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50